'''
Created on 2017-3-3
@author: yimeng
'''
# coding=utf-8
from django.utils.translation import ugettext_lazy as _
__author__ = 'yimeng'

# DB_CHAR_CODE_1 = 1
# DB_CHAR_CODE_2 = 2
# DB_CHAR_CODE_4 = 4
# DB_CHAR_CODE_6 = 6
# DB_CHAR_CODE_8 = 8
# DB_CHAR_CODE_10 = 10
# 
# DB_CHAR_NAME = 20
# DB_CHAR_NAME_40 = 40
# DB_CHAR_NAME_60 = 60
# DB_CHAR_NAME_80 = 80
# DB_CHAR_NAME_120 = 120
# DB_CHAR_NAME_200 = 200

DECIMAL_MAX_DIGITS = 10
DECIMAL_DECIMAL_PLACES = 2


ORDER_STATUS_BUSINESS_PLAN = 10
ORDER_STATUS_BUSINESS_FORMAL = 20

ORDER_STATUS_SELF_PAY = 88

ORDER_STATUS_IN_TRANSIT = 30

ORDER_STATUS_WAREHOUSE_ARRIVAL = 40
ORDER_STATUS_SELF_REJECT = 411
ORDER_STATUS_SELF_REJECT_OK = 4112
ORDER_STATUS_WAREHOUSE_IN = 50
ORDER_STATUS_SELF_RETURN = 53

ORDER_STATUS_WAREHOUSE_PICK = 60
ORDER_STATUS_WAREHOUSE_OUT = 70
ORDER_STATUS_CLIENT_RETURN = 73

ORDER_STATUS_CLIENT_PAY = 80
ORDER_STATUS_CLIENT_RECEIPT = 90
ORDER_STATUS_CLIENT_REJECT = 911

ORDER_STATUS_CANCEL = 30
ORDER_STATUS_SELF_CANCEL = 311
ORDER_STATUS_SELF_CANCEL_OK = 3112
ORDER_STATUS_CLIENT_CANCEL = 321
ORDER_STATUS_CLIENT_CANCEL_OK = 3212

ORDER_STATUS_ERROR = 44


IO_I = 'I'
IO_O = 'O'

ORDER_STATUS_CHOICES = (
    (ORDER_STATUS_BUSINESS_PLAN,_('plan')),
    (ORDER_STATUS_BUSINESS_FORMAL,_('formal order')),
    
    (ORDER_STATUS_SELF_PAY,_('self pay')),
    
    (ORDER_STATUS_IN_TRANSIT,_('in transit')),
    
    (ORDER_STATUS_WAREHOUSE_ARRIVAL,_('warehouse arrival')),
    (ORDER_STATUS_SELF_REJECT,_('self reject')),
    (ORDER_STATUS_SELF_REJECT_OK,_('confirm self reject')),
    (ORDER_STATUS_WAREHOUSE_IN,_('add stock')),
    (ORDER_STATUS_SELF_RETURN,_('self return')),
    
    (ORDER_STATUS_WAREHOUSE_PICK,_('pick goods')),
    (ORDER_STATUS_WAREHOUSE_OUT,_('minus stock')),
    (ORDER_STATUS_CLIENT_RETURN,_('client return')),
    
    (ORDER_STATUS_CLIENT_PAY,_('client pay')),
    
    (ORDER_STATUS_CLIENT_RECEIPT,_('client receipt')),
    (ORDER_STATUS_CLIENT_REJECT, _('client reject')),
    (ORDER_STATUS_CANCEL,_('cancel')),
    (ORDER_STATUS_SELF_CANCEL,_('self cancel')),
    (ORDER_STATUS_SELF_CANCEL_OK,_('confirm self cancel')),
    (ORDER_STATUS_CLIENT_CANCEL,_('client cancel')),
    (ORDER_STATUS_CLIENT_CANCEL_OK,_('confirm client cancel')),
    
    (ORDER_STATUS_ERROR,_('error')),
)


